### ISSUE TITLE
Unable to Open Attachment in IDMS when transfered from PRe-Order workflow

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/POWorkFlow#1]
@sagar-isgec , check and fix this issue

**Comment by sagar-isgec** [comment]
Issue:- Code.

Fix:
Use exsisting Document ID as 
 string sDocumentId = dt.Rows[0]["t_dcid"].ToString();
and uncomment following line of code
string sDocumentId = "AAA" + nRecord;

Please review code changes @hariharan-isgec

**Comment by sagar-isgec** [comment]
Changes have been successfully tested by Pankaj Sir.
