### ISSUE TITLE
Email Alert for PPM

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/POWorkFlow#2]
Email Alert required to PPM on Release Technical Specification and Raise Enquiry.

**Comment by veena-isgec** [comment]
@sagar-isgec please copy to live.

**Comment by sagar-isgec** [comment]
Required code changes have been made. I would push it to git hub tomorrow.

**Comment by hariharan-isgec** [comment]
@veena-isgec check and confirm

**Comment by veena-isgec** [comment]
uploaded on live
 working fine.
