### ISSUE TITLE
Modification in RFQ Generation from Indent 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/POWorkFlow#7]
1. Workflow should be generated only when Indent is in Approved Status
2. Workflow should be generated only when Indent has child items in tdisg003
3. BaaN Tables dmisg167, dmisg168, dmisg169 should be populated

**Comment by 0340LalitGupta** [comment]
Issues are addressed in WebCom1 Commit: Modification in RFQ Generation from Indent.

@hariharan-isgec 
Pl. close this Issue.
